config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(pagina/:page)", action: :index, on: :collection, as: ""
  end

  root "pages#index"

  get "up", to: "rails/health#show", as: :rails_health_check
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # User and session
  resources :sessions, only: [:create, :destroy]

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  # Books and related
  resources :authors, path: "naam", param: :slug, only: [:show]
  resources :genres, param: :slug, only: [:show]

  get "boek/:slug_and_isbn", to: "books#show", as: :book
  get "boeken", to: "books#index", as: :books, concerns: :paginatable

  get "book/listings/:slug_and_isbn", to: "books#listings_summary_partial", as: :book_listings_summary
  get "book/request_scrape/:slug_and_isbn", to: "books#request_scrape", as: :book_request_scrape

  # Actions
  get "actions/index_by_isbn/:isbn", to: "actions#index_by_isbn"
  post "actions/attach_image_for_isbn", to: "actions#attach_image_for_isbn", as: :attach_image_for_isbn
  post "actions/run_all_scrapers_for_isbn", to: "actions#run_all_scrapers_for_isbn", as: :run_all_scrapers_for_isbn
  post "actions/generate_ai_description_for_isbn", to: "actions#generate_ai_description_for_isbn", as: :generate_ai_description_for_isbn
  post "actions/generate_ai_keywords_for_isbn", to: "actions#generate_ai_keywords_for_isbn", as: :generate_ai_keywords_for_isbn
  post "actions/generate_ai_description_for_author", to: "actions#generate_ai_description_for_author", as: :generate_ai_description_for_author

  # Pages
  get "over-ons", to: "pages#about", as: :about

  namespace :admin do
    get "/", to: "base#index", as: :root

    resources :books, param: :slug_and_isbn
    resources :listings
    resources :sources, param: :slug
    resources :genres, param: :slug
    resources :authors, param: :slug
    resources :users
  end

  direct :rails_public_blob do |blob|
    if ENV["CDN"].present?
      File.join(ENV["CDN"], blob.key)
    else
      url_for(blob)
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  include ApplicationHelper

  if ENV["BONSAI_URL"]
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    settings index: { number_of_shards: 1 }
  end

  has_many :listings, dependent: :destroy
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_many :book_genres, dependent: :destroy
  has_many :genres, through: :book_genres

  has_one_attached :cover_image do |attachable|
    attachable.variant(:large, resize_to_limit: [300, 500], quality: 80, format: :webp, preprocessed: true)
    attachable.variant(:small, resize_to_limit: [250, 190], quality: 80, format: :webp, preprocessed: true)
  end

  enum :format, [:unknown, :paperback, :hardcover], suffix: true
  enum :language, { dutch: "nl", english: "en" }

  validates :title, presence: true
  validates :isbn, presence: true, uniqueness: true, format: { with: /\A\d{13}\z/ }
  validates :format, inclusion: { in: Book.formats.keys }
  validates :language, inclusion: { in: Book.languages.keys }, allow_nil: true
  validates :published_date_text, format: { with: /\A[0-9\-]+\z/ }, allow_nil: true, allow_blank: true

  accepts_nested_attributes_for :book_authors, allow_destroy: true
  accepts_nested_attributes_for :book_genres, allow_destroy: true

  def to_param
    "#{title.parameterize}-#{isbn}"
  end

  def self.full_join
    self.includes(:authors, listings: :source, cover_image_attachment: :blob)
        .references(:authors, :listings, :source)
  end

  def listings_with_price
    listings.includes(:source).where.not(price: 0).where(available: true)
  end

  def listings_with_price_sorted
    listings_with_price.to_a.sort_by { |listing| [listing.price, listing.shipping_cost_actual, listing.source.name] }
  end

  def lowest_price
    listings_with_price.pluck(:price).sort.first
  end

  def cheapest_listing
    listings_with_price.sort_by(&:price).first
  end

  def authors_human_list
    human_list(authors.pluck(:name))
  end

  def requires_scrape?
    # Requires scrape if scrape is not ongoing
    !is_scrape_ongoing? &&
    # and a scrape has never been started, or the last scrape is past the threshold.
    (last_scrape_started_at.blank? || (last_scrape_finished_at.present? && last_scrape_finished_at < 1.day.ago))
  end

  def is_scrape_ongoing?
    return false if last_scrape_started_at.blank?

    # Check if a scrape is ongoing either by checking if a start datetime exists without an end datetime,
    (last_scrape_started_at.present? && last_scrape_finished_at.blank?) ||
    # or by checking if the finished datetime is before the end datetime, indicating that it has not yet finished.
    (last_scrape_finished_at.present? && (last_scrape_finished_at < last_scrape_started_at))
  end

  def should_show_scrape_message?
    (requires_scrape? || is_scrape_ongoing?) &&
    # Only show message if book has never been scraped or last scrape is more than 2 days ago.
    # A scrape might still happen if it's earlier (see requires_scrape?), but we won't show a message or update the page.
    (last_scrape_finished_at.nil? || (last_scrape_finished_at.present? && last_scrape_finished_at < 2.days.ago))
  end

  # Returns a - if no number of pages are given, otherwise return a number with "." for the thousands delimiter,
  # as that is what is used in Dutch rather than commas.
  def formatted_number_of_pages
    self.number_of_pages.zero? ? "-" : number_with_delimiter(self.number_of_pages, delimiter: ".")
  end

  # The published_date_text is nothing but a string, but it only allows numbers and dashes.
  # Return date either as "5 April, 2025" or only the year "2025", depending on how much is available.
  # If the string is just 4 characters we assume it's nothing but a year, which is sometimes all we get.
  def formatted_published_date
    return if self.published_date_text.blank?

    return self.published_date_text if self.published_date_text.length === 4 # It's probably a year

    parts = self.published_date_text.split("-").map(&:to_i)
    I18n.l(Date.new(parts[0], parts[1], parts[2]), format: "%-d %B, %Y")
  end

  def published_year
    return if self.published_date_text.blank?

    return self.published_date_text if self.published_date_text.length === 4 # It's probably a year

    parts = self.published_date_text.split("-").map(&:to_i)
    parts[0]
  end

  # Keywords are a comma separated list, use this method to get them as an array
  def separated_keywords
    keywords.to_s.split(",").map(&:strip)
  end

  # When an image is attached it's height and width are saved. This is used to an
  # aspect ratio so that when an image loads it can show in the correct dimensions
  # before it has finished loading.
  def cover_aspect_ratio
    return "" if cover_original_width.blank? || cover_original_height.blank?
    "#{cover_original_width} / #{cover_original_height}"
  end

  # TODO: Add proper translation keys, this will do just fine for now though.
  def language_label
    language === "english" ? "Engels" : "Nederlands"
  end

  def format_label
    return "Hardcover" if hardcover_format?
    return "Paperback" if paperback_format?
    "Onbekend"
  end

  # Consists of 3 matchers;
  # 1. If the search result consists of nothing but 13 numbers, we assume it's an isbn and search just by that
  # 2. Large weight towards title and no fuzziness. This should prioritize exact matches of the title (or author).
  # 3. Fuzzy search for all records by their relevant fields. This includes keywords, genres, and genre keywords.
  def self.search(query, size: 50)
    is_isbn = query.match?(/\A\d{13}?\z/)

    __elasticsearch__.search({
      from: 0,
      size: size,
      query: {
        bool: {
          should: [
            (is_isbn ? { term: { isbn: query } } : nil),
            {
              multi_match: {
                query: query,
                fields: [
                  "title"
                ],
                type: "cross_fields",
                operator: "and",
                tie_breaker: 0.1,
                boost: 100,
                minimum_should_match: "50%"
              }
            },
            {
              function_score: {
                query: {
                  multi_match: {
                    query: query,
                    fields: [
                      "title^3",
                      "authors^2.5",
                      "keywords^2.5",
                      "genres^1.5",
                      "genre_keywords"
                    ],
                    fuzziness: "AUTO"
                  }
                },
                boost_mode: "sum",
                max_boost: 2
              }
            }
          ].compact
        }
      }
    }).records
  end

  def as_indexed_json(_options = {})
    {
      isbn: isbn,
      title: title,
      keywords: keywords,
      authors: authors.map(&:name),
      genres: genres.map(&:name),
      genre_keywords: genres.flat_map { |g| g.keywords.to_s.split(",").map(&:strip) }
    }
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.order(created_at: :desc).page(params[:page])
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to [:admin, @book], notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      redirect_to [:admin, @book], notice: "Book was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy!
    redirect_to admin_books_path, notice: "Book was successfully destroyed.", status: :see_other
  end

  private

  def set_book
    isbn = params.expect([:slug_and_isbn]).split("-").last
    @book = Book.find_by_isbn!(isbn)
  end

  def book_params
    params.expect(book: [
      :title, :subtitle, :description,
      :format, :condition, :language,
      :isbn, :number_of_pages, :published_date_text,
      author_ids: [], genre_ids: []
    ])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :listings_summary_partial, :request_scrape]
  before_action :redirect_isbn, only: [:index]

  # after_action :request_description, only: [:show]
  # after_action :request_cover, only: [:show]

  def index
    @books = BookFilter.new(Book.full_join, filter_params).filter.page(params[:page])

    @genres = Genre.includes(subgenres: { subgenres: { subgenres: :subgenres } }).where(parent_genre_id: nil)
  end

  def show
  end

  # A js request is made to this method when book.requires_scrape? is true.
  # This is done through js rather than before_action so as not to call it on prefetch or when bots visit the page.
  def request_scrape
    return unless @book.requires_scrape?

    puts "Requested new scrape"

    RequestScrapeJob.perform_later(@book.isbn)
  end

  def listings_summary_partial
    return head :no_content if @book.requires_scrape? || @book.is_scrape_ongoing?

    render partial: "book_listings_summary"
  end

  private

  def set_book
    isbn = params.expect([:slug_and_isbn]).split("-").last
    @book = Book.full_join.find_by_isbn!(isbn)
    @listings = @book.listings_with_price_sorted
  end

  def redirect_isbn
    return unless params[:query]

    is_isbn = params[:query].match?(/\A97[89]\d{10}\z/)

    return unless is_isbn

    book = Book.find_by_isbn(params[:query])

    redirect_to book if book.present?
  end

  def request_description
    # Stop if there are no listings with descriptions or a description has already been generated.
    return if @book.listings.where.not(description: nil).none?
    return if @book.description_last_generated_at.present?

    puts "Requested new description"

    RequestDescriptionJob.perform_later(@book.isbn)
  end

  def request_cover
    # Stop if book already has a cover of if it has attempted to get the cover before.
    # It's possible a book simply has no cover on Goodreads, in which case we don't want
    # to keep retrying for each request.
    return if @book.cover_image.attached?
    return if @book.cover_last_scraped_at.present?

    puts "Requested new cover"

    RequestCoverJob.perform_later(@book.isbn)
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def book_listings_to_summary(book)
    return "\"#{@book.title}\" is helaas op het moment nergens beschikbaar. Het kan zijn dat wij het nog aan het indexeren zijn." if book.listings_with_price.empty?

    sorted = book.listings_with_price.sort_by(&:price)
    cheapest_listing = sorted.first
    cheapest_price = cheapest_listing.price_label
    cheapest_source = cheapest_listing.source.name

    # Boek, door auteurs, is het allergoedkoopst bij Verkoper, voor maar €12.34.
    # Optional if cheapest condition is known: Dit boek wordt als conditie verkocht
    # Optional if cheapest is not new condition: Daarnaast is het ook nieuw te vinden bij Verkoper voor €12.34.
    # Optional if more listings are given: Ook is het te vinden bij Verkoper voor €12.34.
    first_sentence = <<~HTML.strip
      #{book.title}#{", door #{human_list(book.authors.pluck(:name))}," if book.authors.any?} is het allergoedkoopst bij #{cheapest_source}, voor maar #{cheapest_price}. #{listing_condition_sentence(cheapest_listing)} #{new_listings_note(sorted, cheapest_listing)}
    HTML

    other_listings = sorted.reject { |l| l == cheapest_listing }

    if other_listings.any?
      other_sentence = "Ook is het te vinden bij " +
        other_listings.map do |listing|
          price = listing.price_label
          "#{listing.source.name} voor #{price}#{listing.unknown_condition? ? "" : " (#{listing.condition_label.downcase})"}"
        end.to_sentence + "."
    else
      other_sentence = ""
    end

    first_sentence + "\n\n" + other_sentence.gsub(", and ", " en ") # Cheapo i18n
  end

  private

  # The second sentence, explaining the conditions. Can be empty if no condition is known.
  # Sentence should start with a space.
  def listing_condition_sentence(listing)
    return "" if listing.unknown_condition?
    " Dit boek wordt als #{listing.condition_label.downcase} verkocht."
  end

  # Return a sentence as a "new" alternative to a second hand book
  def new_listings_note(listings, cheapest_listing)
    return "" if cheapest_listing.new_condition?

    new_listings = listings.select { |l| l.new_condition? && l != cheapest_listing }

    return "" if new_listings.empty?

    listing = new_listings.first
    source = listing.source.name
    price = listing.price_label

    "Daarnaast is het ook nieuw te vinden bij #{source} voor #{price} euro."
  end
end

app/views/admin/books/_book.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Authors:</strong>
    <% book.authors.each do |author| %>
      <span><%= author.name %></span>
    <% end %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= book.isbn %>
  </p>

  <p>
    <strong>Number of listings:</strong>
    <%= book.listings_with_price.size %>
  </p>

  <%= link_to "Show this book", admin_book_path(book) %>

  <hr>
</div>

app/views/admin/books/_form.html.erb
<%= form_with(model: [:admin, book]) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn, class: "form-input" %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-input" %>
  </div>

  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle, class: "form-input" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-input" %>
  </div>

  <div>
    <%= form.label :author_ids, "Authors", style: "display: block" %>
    <%= form.collection_select :author_ids, Author.all, :id, :name, {}, { multiple: true, size: 5, class: "form-input" } %>
  </div>

  <div>
    <%= form.label :genre_ids, "Genres", style: "display: block" %>
    <%= form.collection_select :genre_ids, Genre.all, :id, :name, {}, { multiple: true, size: 5, class: "form-input" } %>
  </div>

  <div>
    <%= form.label :number_of_pages, style: "display: block" %>
    <%= form.number_field :number_of_pages, class: "form-input" %>
  </div>

  <div>
    <%= form.label :format, "Format", style: "display: block" %>
    <%= form.select :format, Book.formats.keys.map { |f| [f.titleize, f] }, { prompt: "Select a format" }, { class: "form-input" } %>
  </div>

  <div>
    <%= form.label :language, "Language", style: "display: block" %>
    <%= form.select :language, Book.languages.keys.map { |f| [f.titleize, f] }, { prompt: "Select a language" }, { class: "form-input" } %>
  </div>

  <div>
    <%= form.label :published_date_text, style: "display: block" %>
    <%= form.text_field :published_date_text, class: "form-input" %>
  </div>

  <div class="mt-1">
    <%= form.submit "Submit", class: "button button--primary" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<%= render "admin/layout", heading: "Edit book #{@book.title} by #{@book.authors_human_list}" do %>
  <%= render "form", book: @book %>

  <br>

  <div>
    <%= link_to "Show this book", @book %> |
    <%= link_to "Back to books", books_path %>
  </div>
<% end %>

app/views/admin/books/index.html.erb
<%= render "admin/layout", heading: "Books" do %>
  <%= link_to "Create new book", new_admin_book_path, class: "button button--primary" %>

  <hr>

  <%= page_entries_info @books %>

  <hr>


  <%= render @books %>

  <%= paginate @books %>
<% end %>

app/views/admin/books/new.html.erb
<%= render "admin/layout", heading: "Add new book" do %>
  <%= render "form", book: @book %>

  <br>

  <div>
    <%= link_to "Back to books", books_path %>
  </div>
<% end %>

app/views/admin/books/show.html.erb
<%= render "admin/layout", heading: "Book | #{@book.title}" do %>
  <h2 class="text-transform-none"><%= @book.title %></h2>

  <%= tag.h3 @book.subtitle, class: "text-transform-none" if @book.subtitle %>

  <p><%= @book.isbn %></p>

  <% @book.authors.each do |author| %>
    <span><%= author.name %></span>
  <% end %>

  <hr>

  <div class="button-group">
    <%= link_to "Back to overview", admin_books_path, class: "button" %>
    <%= link_to "View book page", @book, class: "button" %>
    <%= link_to "Edit this book", edit_admin_book_path(@book), class: "button" %>

    <%= button_to "Destroy this book", [:admin, @book], method: :delete, class: "button button--danger", data: { turbo_confirm: "Are you sure you wish to destroy this book?" } %>
  </div>

  <hr>

  <h3 class="text-transform-none">Description:</h3>

  <div class="description">
    <% if @book.description.present? %>
      <%= simple_format(@book.description) %>
    <% else %>
      -
    <% end %>
  </div>

  <%= button_to "(re)Generate description",
                generate_ai_description_for_isbn_path,
                class: "button",
                params: { isbn: @book.isbn },
                data: { turbo_submits_with: "Running..." },
                method: :post %>

  <hr>

  <h3 class="text-transform-none">Cover image:</h3>

  <figure>
    <% if @book.cover_image.attached? %>
      <%= image_tag rails_public_blob_url(@book.cover_image.variant(:large).processed) %>
    <% else %>
      No image
    <% end %>
  </figure>

  <%= button_to "(re)Get cover image for this book",
                attach_image_for_isbn_path,
                class: "button",
                params: { isbn: @book.isbn },
                data: { turbo_submits_with: "Running..." },
                method: :post %>

  <hr>

  <h3 class="text-transform-none">General details:</h3>

  <p>
    <strong>Genres:</strong>
    <% @book.genres.each do |genre| %>
      <span><%= genre.name %></span>
    <% end %>
  </p>

  <p>
    <strong>Keywords:</strong>
    <%= @book.keywords %>
    <%= button_to "(re)Generate keywords",
                  generate_ai_keywords_for_isbn_path,
                  class: "button",
                  params: { isbn: @book.isbn },
                  data: { turbo_submits_with: "Running..." },
                  method: :post %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
  </p>

  <p>
    <strong>Number of pages:</strong>
    <%= @book.formatted_number_of_pages %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= @book.language %>
  </p>

  <p>
    <strong>Format:</strong>
    <%= @book.format %>
  </p>

  <p>
    <strong>Published date:</strong>
    <% if @book.published_date_text %>
      <%= @book.formatted_published_date %>
      (<%= @book.published_date_text %>)
    <% end %>
  </p>

  <p>
    <strong>Hotness:</strong>
    <%= @book.hotness %>
  </p>

  <p>
    <strong>Scrape last started at:</strong>
    <%= @book.last_scrape_started_at || "Never" %>
    <br>
    <strong>Scrape last finished at:</strong>
    <%= @book.last_scrape_finished_at || "Never" %>
    <%= button_to "Scrape now",
                  run_all_scrapers_for_isbn_path,
                  class: "button",
                  params: { isbn: @book.isbn },
                  data: { turbo_submits_with: "Running..." },
                  method: :post %>
  </p>

  <hr>

  <h3 class="text-transform-none">Listings:</h3>

  <% @book.listings.each do |listing| %>
    <%= render listing, partial: "admin/listings/listing" %>
    <hr>
  <% end %>
<% end %>