config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(pagina/:page)", action: :index, on: :collection, as: ""
  end

  root "pages#index"

  get "up", to: "rails/health#show", as: :rails_health_check
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # User and session
  resources :sessions, only: [:create, :destroy]

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  # Books and related
  resources :authors, path: "naam", param: :slug, only: [:show]
  resources :genres, param: :slug, only: [:show]

  get "boek/:slug_and_isbn", to: "books#show", as: :book
  get "boeken", to: "books#index", as: :books, concerns: :paginatable

  get "book/listings/:slug_and_isbn", to: "books#listings_summary_partial", as: :book_listings_summary
  get "book/request_scrape/:slug_and_isbn", to: "books#request_scrape", as: :book_request_scrape

  # Actions
  get "actions/index_by_isbn/:isbn", to: "actions#index_by_isbn"
  post "actions/attach_image_for_isbn", to: "actions#attach_image_for_isbn", as: :attach_image_for_isbn
  post "actions/run_all_scrapers_for_isbn", to: "actions#run_all_scrapers_for_isbn", as: :run_all_scrapers_for_isbn
  post "actions/generate_ai_description_for_isbn", to: "actions#generate_ai_description_for_isbn", as: :generate_ai_description_for_isbn
  post "actions/generate_ai_keywords_for_isbn", to: "actions#generate_ai_keywords_for_isbn", as: :generate_ai_keywords_for_isbn
  post "actions/generate_ai_description_for_author", to: "actions#generate_ai_description_for_author", as: :generate_ai_description_for_author

  # Pages
  get "over-ons", to: "pages#about", as: :about

  namespace :admin do
    get "/", to: "base#index", as: :root

    resources :books, param: :slug_and_isbn
    resources :listings
    resources :sources, param: :slug
    resources :genres, param: :slug
    resources :authors, param: :slug
    resources :users
  end

  direct :rails_public_blob do |blob|
    if ENV["CDN"].present?
      File.join(ENV["CDN"], blob.key)
    else
      url_for(blob)
    end
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_paper_trail

  belongs_to :book
  belongs_to :source

  enum :condition, [:unknown, :new, :used, :damaged], suffix: true

  validates :currency, inclusion: { in: VALID_CURRENCIES, message: "%{value} is not a valid currency" }, allow_nil: true
  validates :condition, inclusion: { in: Listing.conditions.keys }

  def price_large
    price.to_s.split(".")[0]
  end

  def price_cents
    cents = price.to_s.split(".")[1]

    return cents + "0" if cents.size == 1
    cents
  end

  def price_label
    "€#{price_large},#{price_cents}"
  end

  def shipping_cost_actual
    # If the listing price includes shipping or if the price includes the sources free shipping cost threshold
    return 0 if price_includes_shipping? || (source.shipping_cost_free_from_price > 0 && price >= source.shipping_cost_free_from_price)
    source.shipping_cost
  end

  def shipping_label
    return "Gratis verzending" if shipping_cost_actual == 0
    "+€#{format("%.2f", shipping_cost_actual).gsub(".", ",")} verzenden"
  end

  def condition_label
    return "Nieuw" if new_condition?
    return "Tweedehands" if used_condition?
    return "Licht beschadigd" if damaged_condition?
    "Onbekend"
  end
end

app/controllers/admin/listings_controller.rb
class Admin::ListingsController < Admin::BaseController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.all.page(params[:page])
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to [:admin, @listing], notice: "Listing was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to [:admin, @listing], notice: "Listing was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    book = @listing.book

    @listing.destroy!
    redirect_to [:admin, book], notice: "Listing was successfully destroyed.", status: :see_other
  end

  private

  def set_listing
    @listing = Listing.find(params.expect(:id))
  end

  def listing_params
    params.expect(listing: [:book_id, :source_id, :price, :condition, :condition_details, :currency, :url, :last_scraped_at])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.all.page(params[:page])
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      redirect_to @listing, notice: "Listing was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: "Listing was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    book = @listing.book

    @listing.destroy!
    redirect_to book, notice: "Listing was successfully destroyed.", status: :see_other
  end

  private

  def set_listing
    @listing = Listing.find(params.expect(:id))
  end

  def listing_params
    params.expect(listing: [:book_id, :source_id, :price, :condition, :condition_details, :currency, :url, :last_scraped_at])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/admin/listings/_form.html.erb
<%= form_with(model: [:admin, listing]) do |form| %>
  <% if listing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id %>
   <%= form.collection_select :book_id, Book.all, :id, :title, { prompt: "Select a Book" }, { class: "form-input" } %>
  </div>

  <div>
    <%= form.label :source_id %>
    <%= form.collection_select :source_id, Source.all, :id, :name, { prompt: "Select a Source" }, { class: "form-input" } %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-input" %>
  </div>

  <div>
    <%= form.label :currency %>
    <%= form.text_field :currency, class: "form-input" %>
  </div>

  <div>
    <%= form.label :condition, "Condition" %>
    <%= form.select :condition, Listing.conditions.keys.map { |f| [f.titleize, f] }, { prompt: "Select a condition" }, { class: "form-input" } %>
  </div>

  <div>
    <%= form.label :condition_details %>
    <%= form.text_field :condition_details, class: "form-input" %>
  </div>

  <div>
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-input" %>
  </div>

  <div>
    <%= form.label :last_scraped_at %>
    <%= form.datetime_field :last_scraped_at, class: "form-input" %>
  </div>

  <div class="mt-1">
    <%= form.submit "Submit", class: "button button--primary" %>
  </div>
<% end %>

app/views/admin/listings/_listing.html.erb
<div id="<%= dom_id listing %>" style="opacity: <%= listing.available? ? 1 : 0.5 %>">
  <p>
    <strong>Book:</strong>
    <%= listing.book.title %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= listing.source.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_with_precision(listing.price, precision: 2) %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= listing.currency %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= listing.condition %>
    <%= tag.span "(#{listing.condition_details})" if listing.condition_details.present? %>
  </p>

  <p>
    <strong>Number of pages:</strong>
    <%= listing.number_of_pages %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= listing.description %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= link_to listing.url, listing.url, target: "_blank", ref: "noreferral nofollow" if listing.url.present? %>
  </p>

  <p>
    <strong>Last scraped at:</strong>
    <%= listing.last_scraped_at %>
  </p>

  <p>
    <strong>Was last scrape successful:</strong>
    <%= listing.was_last_scrape_successful %>
  </p>

  <%= link_to "View listing", [:admin, listing] %>
</div>

app/views/admin/listings/edit.html.erb
<%= render "admin/layout", heading: "Edit listing #{@listing.id} for #{@listing.book.title}" do %>
  <%= render "form", listing: @listing %>

  <br>

  <div>
    <%= link_to "Show this listing", [:admin, @listing] %> |
    <%= link_to "Back to listings", admin_listings_path %>
  </div>
<% end %>

app/views/admin/listings/index.html.erb
<%= render "admin/layout", heading: "Listings" do %>
  <%= page_entries_info @listings %>

  <hr>

  <%= link_to "Create new listing", new_admin_listing_path, class: "button button--primary" %>

  <%= render @listings %>

  <%= paginate @listings %>
<% end %>

app/views/admin/listings/new.html.erb
<%= render "admin/layout", heading: "New listing" do %>
  <%= render "form", listing: @listing %>

  <br>

  <div>
    <%= link_to "Back to listings", admin_listings_path %>
  </div>
<% end %>

app/views/admin/listings/show.html.erb
<%= render "admin/layout", heading: "Listing for #{@listing.book.title}" do %>
  <%= render @listing %>

  <%= @listing.versions.size %>

  <h2>Price history</h2>

  <% @listing.versions.each do |version| %>
    <%= version.reify&.price %>
  <% end %>

  <%= @listing.price %>

  <div>
    <%= link_to "Edit this listing", edit_admin_listing_path(@listing) %> |
    <%= link_to "Back to listings", admin_listings_path %>

    <%= button_to "Destroy this listing", [:admin, @listing], method: :delete %>
  </div>
<% end %>