config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get "(pagina/:page)", action: :index, on: :collection, as: ""
  end

  root "pages#index"

  get "up", to: "rails/health#show", as: :rails_health_check
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # User and session
  resources :sessions, only: [:create, :destroy]

  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  # Books and related
  resources :authors, path: "naam", param: :slug, only: [:show]
  resources :genres, param: :slug, only: [:show]

  get "boek/:slug_and_isbn", to: "books#show", as: :book
  get "boeken", to: "books#index", as: :books, concerns: :paginatable

  get "book/listings/:slug_and_isbn", to: "books#listings_summary_partial", as: :book_listings_summary
  get "book/request_scrape/:slug_and_isbn", to: "books#request_scrape", as: :book_request_scrape

  # Actions
  get "actions/index_by_isbn/:isbn", to: "actions#index_by_isbn"
  post "actions/attach_image_for_isbn", to: "actions#attach_image_for_isbn", as: :attach_image_for_isbn
  post "actions/run_all_scrapers_for_isbn", to: "actions#run_all_scrapers_for_isbn", as: :run_all_scrapers_for_isbn
  post "actions/generate_ai_description_for_isbn", to: "actions#generate_ai_description_for_isbn", as: :generate_ai_description_for_isbn
  post "actions/generate_ai_keywords_for_isbn", to: "actions#generate_ai_keywords_for_isbn", as: :generate_ai_keywords_for_isbn
  post "actions/generate_ai_description_for_author", to: "actions#generate_ai_description_for_author", as: :generate_ai_description_for_author

  # Pages
  get "over-ons", to: "pages#about", as: :about

  namespace :admin do
    get "/", to: "base#index", as: :root

    resources :books, param: :slug_and_isbn
    resources :listings
    resources :sources, param: :slug
    resources :genres, param: :slug
    resources :authors, param: :slug
    resources :users
  end

  direct :rails_public_blob do |blob|
    if ENV["CDN"].present?
      File.join(ENV["CDN"], blob.key)
    else
      url_for(blob)
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres
  has_many :books, through: :book_genres
  has_many :subgenres, class_name: "Genre", foreign_key: "parent_genre_id", dependent: :nullify

  belongs_to :parent_genre, class_name: "Genre", optional: true

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  def to_param
    slug
  end

  # Keywords are a comma separated list, use this method to get them as an array
  def separated_keywords
    keywords.to_s.split(",").map(&:strip)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def show
  end

  def new
    @genre = Genre.new
  end

  def edit
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to [:admin, @genre], notice: "Genre was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @genre.update(genre_params)
      redirect_to [:admin, @genre], notice: "Genre was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.destroy!
    redirect_to admin_genres_path, notice: "Genre was successfully destroyed.", status: :see_other
  end

  private

  def set_genre
    @genre = Genre.find_by_slug!(params.expect(:slug))
  end

  def genre_params
    params.expect(genre: [:name, :slug, :parent_genre_id, :keywords])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show]

  def show
    @hot_books = @genre.books.full_join.includes(:authors, :listings).order(hotness: :desc).limit(8)
    @subgenres = @genre.subgenres
  end

  private

  def set_genre
    @genre = Genre.includes(:books).find_by_slug!(params.expect(:slug))
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with(model: [:admin, genre]) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-input" %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug, class: "form-input" %>
  </div>

  <div>
    <%= form.label :parent_genre_id, style: "display: block" %>
    <%= form.collection_select :parent_genre_id, Genre.all, :id, :name, { include_blank: "None" }, { class: "form-input" } %>
  </div>

  <div>
    <%= form.label :keywords, style: "display: block" %>
    <%= form.text_field :keywords, class: "form-input" %>
  </div>

  <div class="mt-1">
    <%= form.submit "Submit", class: "button button--primary" %>
  </div>
<% end %>

app/views/admin/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p>
    <strong>Name:</strong>
    <%= link_to genre.name, [:admin, genre] %>
  </p>

  <p>
    <strong>Parent genre:</strong>
    <%= genre.parent_genre.name if genre.parent_genre.present? %>
  </p>

  <p>
    <strong>Keywords:</strong>
    <%= genre.keywords %>
  </p>

  <p>
    <strong>Book with genre:</strong>
    <%= genre.books.size %>
  </p>

  <% genre.subgenres.each do |genre| %>
    <div style="padding-left: 2rem">
      <%= render genre %>
    </div>
  <% end %>
</div>

app/views/admin/genres/edit.html.erb
<%= render "admin/layout", heading: "Edit genre #{@genre.name}" do %>
  <%= render "form", genre: @genre %>

  <br>

  <div>
    <%= link_to "Show this genre", [:admin, @genre] %> |
    <%= link_to "Back to genres", admin_genres_path %>
  </div>
<% end %>

app/views/admin/genres/index.html.erb
<%= render "admin/layout", heading: "Genres" do %>
  <%= link_to "New genre", new_admin_genre_path, class: "button button--primary" %>

  <hr>

  <div id="genres">
    <% @genres.where(parent_genre: nil).each do |genre| %>
      <%= render genre %>
    <% end %>
  </div>
<% end %>

app/views/admin/genres/new.html.erb
<%= render "admin/layout", heading: "New genre" do %>
  <%= render "form", genre: @genre %>

  <br>

  <div>
    <%= link_to "Back to genres", genres_path %>
  </div>
<% end %>

app/views/admin/genres/show.html.erb
<%= render "admin/layout", heading: "Genre #{@genre.name}" do %>
  <%= render @genre %>

  <div>
    <%= link_to "Edit this genre", edit_admin_genre_path(@genre) %> |
    <%= link_to "Back to genres", admin_genres_path %>

    <%= button_to "Destroy this genre", [:admin, @genre], method: :delete %>
  </div>
<% end %>